spring:
  profiles:
    active: standalone
  datasource:
    # DB_CLOSE_ON_EXITã€€is false? true?
    url: jdbc:h2:mem:~/test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

liquibase:
  enabled: true
  change-log: classpath:db/changelog-master.xml

security:
  user:
    name: "i5"
    password: "Sea++1e"
    role: "first-guest"

poller:
  polling:
    address: "https://www.okex.com/api/spot/v3/instruments/"
    rate: 101
  spotDepths:
    -
      instrument: "BTC-USDT"
      size: 200
      depth: 0.1
    -
      instrument: "ETH-USDT"
      size: 200
      depth: 0.1

task-scheduler:
  write-csv:
    rate: 200

csv:
  order-book:
    address: "./"